"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$kubernetes\
$aws\
$terraform\
$time
$character"""

add_newline = false

[username]
style_user = "green"
style_root = "red"
format = "[ $user]($style)  "
show_always = true

[directory]
format = "[󰉋 $path]($style)  "
style = "#FFA500"
truncation_length = 4
truncate_to_repo = false

[git_branch]
format = "[ $branch]($style) "
style = "bright-white"

[git_status]
format = "([$all_status$ahead_behind]($style))  "
style = "red bold"

[kubernetes]
disabled = false
format = "[󱃾 $context( \\($namespace\\))]($style)  "
style = "cyan"

[aws]
format = "[ $profile]($style)[  $region]($style)  "
style = "yellow"

[terraform]
format = "[󱁢 $workspace]($style)  "
style = "purple"

[character]
success_symbol = "[❯]( white)"
error_symbol = "[❯]( red)"
